simpleblog/post/models.py
from sqlalchemy import Column,Integer,String,DateTime,Text,ForeignKey
from sqlalchemy.orm import relationship, backref
from datetime import datetime
from simpleblog.dbsettings import Base

class Tag(Base):
	__tablename__ = 'Tag'
	tId = Column(Integer, primary_key = True)
	name = Column(String(20))
	postId = Column(Integer,ForeignKey('Post.pId'))

	def __init__(self, name):
		self.name = name

	def __repr__(self):
		return self.name

	def __unicode__(self):
		return self.name


class Post(Base):
	__tablename__ = 'Post'
	pId = Column(Integer, primary_key = True)
	title = Column(String(100))
	publishTime = Column(DateTime, default = datetime.utcnow)
	modifiedTime = Column(DateTime, default = datetime.utcnow, onupdate=datetime.utcnow)
	content = Column(Text)
	authorId = Column(Integer,default = 1)
	categoryId = Column(Integer,ForeignKey('Category.cId'))
	categories = relationship('Category', backref = 'post')
	tags = relationship('Tag', backref = 'post',order_by = 'Tag.tId')
	comments = relationship('Comment', backref = 'post',order_by = 'Comment.publishTime')

	def __init__(self, title, content):
		self.title = title
		self.content = content

	def __repr__(self):
		return '<Post %r>' % (self.title)

	@classmethod
	def findById(cls, id):
		return Post.query.filter(Post.pId == id)

simpleblog/post/forms.py
from flask.ext.wtf import Form
from wtforms import TextField, validators, TextAreaField, HiddenField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from simpleblog.post.models import Post
from simpleblog.dbsettings import db_session
from simpleblog.category.models import Category
class PostCreateForm(Form):
	title = TextField('Title', [validators.Required("Please enter a title!"),validators.length(min = 1, max = 100)])
	content = TextAreaField('Content', [validators.Required("Please enter the content!")])
	category = QuerySelectField('Category',query_factory = lambda: db_session.query(Category), get_pk=lambda a: a.cId, get_label=lambda a: a.name)
	tags = TextField ('Taglist(use "." to separate)')

class PostUpdateForm(PostCreateForm):
	id = HiddenField()

simpleblog/post/__init__.py
from simpleblog.post.forms import *
from simpleblog.post.views import *
from simpleblog.post.models import *

simpleblog/post/views/__init__.py
from backend import *
from frontend import *

simpleblog/post/views/backend.py
from flask import Flask,Blueprint,render_template,redirect,url_for,request,session,flash
from simpleblog.post.models import Post,Tag
from simpleblog.account.models import User
from simpleblog.post.forms import PostCreateForm,PostUpdateForm
from simpleblog.dbsettings import db_session

backend = Blueprint("post_backend",__name__,url_prefix="/admin",template_folder='templates')

@backend.route('/', methods=['GET', 'POST'])
@backend.route('/index', methods=['GET', 'POST'])
@backend.route('/post', methods=['GET', 'POST'])
def index():
	if "username" not in session:
		return redirect(url_for('post_frontend.index'))
	admin = User.query.filter_by(userName=session["username"]).first()
	if admin.roleId != 1:
		return redirect(url_for('post_frontend.index'))

	posts = Post.query.all()
	return render_template('post/backend/index.html', posts = posts)



@backend.route('/post/<int:id>/remove', methods=['GET','POST'])
def remove(id):
	if 'username' not in session:
		return redirect(url_for('post_frontend.index'))
	admin = User.query.filter_by(userName=session["username"]).first()
	if admin.roleId != 1:
		return redirect(url_for('post_frontend.index'))
	Tag.query.filter(Tag.postId==id).delete()
	Post.findById(id).delete()
	db_session.commit()
	return redirect(url_for('post_backend.index'))


@backend.route('/post/new', methods = ['GET', 'Post'])
def new():
	if 'username' not in session:
		return redirect(url_for('post_frontend.index'))
	admin = User.query.filter_by(userName=session["username"]).first()
	if admin.roleId != 1:
		return redirect(url_for('post_frontend.index'))
	form = PostCreateForm()
	if form.validate_on_submit():
		tags = form.tags.data
		tag = []
		for newtag in tags.split(",") :
			if len(newtag) <= 20:	
				tag.append(Tag(newtag))
		newPost = Post(form.title.data, form.content.data)
		newPost.categories = form.category.data
		newPost.tags = tag
		newPost.authorId = admin.uId
		db_session.add(newPost)
		db_session.commit()
		return redirect(url_for('post_backend.index'))
	return render_template('post/backend/new.html', form=form)

@backend.route('/post/<int:id>')
def view(id):
	if 'username' not in session:
		return redirect(url_for('post_frontend.index'))
	admin = User.query.filter_by(userName=session["username"]).first()
	if admin.roleId != 1:
		return redirect(url_for('post_frontend.index'))
	post = Post.findById(id).first()
	if not post:
		return NotFound(404)
	return render_template('post/backend/view.html', post = post)

@backend.route('/post/<int:id>/edit',methods = ['GET', 'POST'])
def edit(id):
	if 'username' not in session:
		return redirect(url_for('post_frontend.index'))
	admin = User.query.filter_by(userName=session["username"]).first()
	if admin.roleId != 1:
		return redirect(url_for('post_frontend.index'))

	post = Post.findById(id).first()
	form = PostUpdateForm(request.form,post)
	if form.validate_on_submit():
		Tag.query.filter(Tag.postId==id).delete()
		tags = form.tags.data
		newlist = []

		for newtag in tags.split(",") :
			if len(newtag) <= 20:	
				a = Tag(newtag)
				a.postId = id;
				newlist.append(Tag(a))
		post.title = form.title.data
		post.content = form.content.data
		post.categories = form.category.data

		post.tags = newlist
		db_session.commit()
		return redirect(url_for('post_backend.index'))


	return render_template('post/backend/edit.html', form=form)

simpleblog/post/views/frontend.py
from flask import Flask,Blueprint,render_template,redirect,url_for,request,session,flash
from simpleblog.post.models import Post,Tag
from simpleblog.post.forms import PostCreateForm,PostUpdateForm
from simpleblog.account.models import User
from simpleblog.comment.forms import CommentCreateForm
from simpleblog.dbsettings import db_session
from datetime import datetime

frontend = Blueprint("post_frontend",__name__,template_folder='../templates')

@frontend.route('/', methods=['GET', 'POST'])
@frontend.route('/index', methods=['GET', 'POST'])
def index():
	if 'username' in session:
		user = User.query.filter_by(userName = session['username']).first()
		if user.roleId == 1:
			session["isadmin"] = True
	posts = Post.query.all()
	return render_template('post/index.html', posts = posts)


@frontend.route('/new', methods = ['GET', 'Post'])
def new():
	if 'username' not in session:
		return redirect(url_for('post_frontend.index'))
	user = User.query.filter_by(userName = session['username']).first()
	if user.roleId != 1:
		return redirect(url_for('post_frontend.index'))
	form = PostCreateForm()
	if form.validate_on_submit():
		tags = form.tags.data
		tag = []
		for newtag in tags.split(",") :
			if len(newtag) <= 20:	
				tag.append(Tag(newtag))
		newPost = Post(form.title.data, form.content.data)
		newPost.categories = form.category.data
		newPost.tags = tag
		newPost.authorId = user.uId
		db_session.add(newPost)
		db_session.commit()
		return redirect(url_for('post_frontend.index'))
	return render_template('post/new.html', form=form)

@frontend.route('/post/<int:id>',methods = ['GET', 'Post'])
def view(id):
	if 'username' in session:
		user = User.query.filter_by(userName = session['username']).first()
		session["userid"] = user.uId
		session["roleid"] = user.roleId
	post = Post.findById(id).first()
	form = CommentCreateForm()
	if not post:
		return NotFound(404)

	return render_template('post/view.html', post = post, form = form)

@frontend.route('/post/<int:id>/edit',methods = ['GET', 'POST'])
def edit(id):
	post = Post.findById(id).first()

	form = PostUpdateForm(request.form,post)
	if form.validate_on_submit():
		Tag.query.filter(Tag.postId==id).delete()
		tags = form.tags.data
		newlist = []

		for newtag in tags.split(",") :
			if len(newtag) <= 20:	
				a = Tag(newtag)
				a.postId = id;
				newlist.append(Tag(a))
		post.title = form.title.data
		post.content = form.content.data
		post.categories = form.category.data

		post.tags = newlist
		db_session.commit()
		return redirect(url_for('post_frontend.index'))


	return render_template('post/edit.html', form=form)

simpleblog/post/templates/post/backend/edit.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
<div class="form">
<form action="{{url_for('post_backend.index')}}" method=post>
	<input id="submit" name="submit" type="submit" value="Back">
</form>
<h2 class="form-signin-heading">Edit Post</h2>
<form action="?{{ request.query_string }}" method=post>
	{{ form.hidden_tag() }}

	{{ form.title.label }}
	{{ form.title }}

	{{ form.content.label }}
	{{ form.content }}

	{{ form.category.label }}
	{{ form.category }}
	<br>
	{{ form.tags.label }}
	{{ form.tags }}

	<input class="btn btn-primary btn-block" id="submit" name="submit" type="submit" value="Edit">
</form>
</div>
</div>
{% endblock %}

simpleblog/post/templates/post/backend/index.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
<form action="{{url_for('post_backend.new')}}" method=post>
	<input class="btn btn-danger" id="submit" name="submit" type="submit" value="Add a new post!">
</form>
	<table class="table">
		<tr>
			<th>Post</th>
			<th>Edit</th>
			<th>Delete</th>
		</tr>
		{% for post in posts %}
		<tr>
			<td><a href="{{ url_for('post_backend.view', id=post.pId) }}">{{ post.title }}</a></td>
			<td><a href="{{ url_for('post_backend.edit', id=post.pId) }}">Edit</a></td>
			<td><a href="{{ url_for('post_backend.remove', id=post.pId) }}">Delete</a></td>
		</tr>
		{% endfor %}
	</table>
</div>
{% endblock %}

simpleblog/post/templates/post/backend/new.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
<div class="form">
<form action="{{url_for('post_backend.index')}}" method=post>
	<input id="submit" name="submit" type="submit" value="Back">
</form>
<h2 class="form-signin-heading">Create New Post</h2>
<form action="{{url_for('post_backend.new')}}" method=post>
	{{ form.hidden_tag() }}

	{{ form.title.label }}
	{{ form.title }}
 
	{{ form.content.label }}
	{{ form.content }}
 
	{{ form.category.label }}
	{{ form.category }}
	<br>
	{{ form.tags.label }}
	{{ form.tags }}

	<input class="btn btn-primary btn-block" id="submit" name="submit" type="submit" value="Post">
</form>
</div>
</div>
{% endblock %}

simpleblog/post/templates/post/backend/view.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
<form action="{{url_for('post_backend.index')}}" method=post>
	<input id="submit" name="submit" type="submit" value="Back">
</form>
<div class="page-header">
<h1>{{post.title}}</h1>
</div>



<div class="panel panel-default">
  <div class="panel-body">
<small class="text-center"><h6>Publish time:{{ post.publishTime }}&nbsp;&nbsp; Last edited:{{ post.modifiedTime }}</h6>
<h6 class="text-center">Category:{{ post.categories.name }} &nbsp;&nbsp;Tag:
		{% for tag in post.tags%}		
			{{tag.name}}
		{% endfor %}</h6></small>
<p class="lead">&nbsp;&nbsp;&nbsp;&nbsp;{{ post.content }}</p>
  </div>
</div>
</div>

{% endblock %}

simpleblog/post/templates/post/edit.html
{% extends "base.html" %}
{% block content %}
<div class="container">
<div class="form">

 	{% for message in form.title.errors %}
	<div class="alert alert-danger">
		<strong>Warning!</strong> {{message}}
	</div>
	{% endfor %}
	{% for message in form.content.errors %}
	<div class="alert alert-danger">
		<strong>Warning!</strong> {{message}}
	</div>
	{% endfor %}
<form action="?{{ request.query_string }}" method=post>
<h2 class="form-signin-heading">Edit Post</h2>
    {{ form.hidden_tag() }}
 
    {{ form.title.label }}
    {{ form.title }}
 
    {{ form.content.label }}
    {{ form.content }}
 
    {{ form.category.label }}
    {{ form.category }}
	<br>
    {{ form.tags.label }}
    {{ form.tags }}

	<input class="btn btn-primary btn-block" id="submit" name="submit" type="submit" value="Edit">
</form>
</div>
</div>
{% endblock %}

simpleblog/post/templates/post/index.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
{% for post in posts %}

	<div class="page-header">
	<h1>
		<a href="{{ url_for('post_frontend.view', id=post.pId) }}" style=" text-decoration: none;color: black">{{ post.title}}</a>
		{% if session["isadmin"] %}
		<small><a href="{{ url_for('post_frontend.edit', id=post.pId) }}" class="label label-primary">edit</a></small>
		<h5><small >Category:{{ post.categories}}</small></h5>
		{% endif %}
	</h1>
	</div>

{% endfor %}
	</div>
{% endblock %}

simpleblog/post/templates/post/new.html
{% extends "base.html" %}
{% block content %}
<div class="container">
<div class="form">

	{% for message in form.title.errors %}
	<div class="alert alert-danger">
		<strong>Warning!</strong> {{message}}
	</div>
	{% endfor %}
	{% for message in form.content.errors %}
	<div class="alert alert-danger">
		<strong>Warning!</strong> {{message}}
	</div>
	{% endfor %}

<form action="{{url_for('post_frontend.new')}}" method="post">
<h2 class="form-signin-heading">Create New Post</h2>
	{{ form.hidden_tag() }}
 
    {{ form.title.label }}
    {{ form.title }}
 
    {{ form.content.label }}
    {{ form.content }}
 
    {{ form.category.label }}
    {{ form.category }}

    {{ form.tags.label }}
    {{ form.tags }}
	<br>
	<p><input class="btn btn-success btn-block" id="submit" name="submit" type="submit" value="Post"></p>
</form>
</div>
</div>

{% endblock %}

simpleblog/post/templates/post/view.html
{% extends "base.html" %}
{% block content %}
<div class="container">

<form action="{{url_for('post_frontend.index')}}" method=post>
	<input id="submit" name="submit" type="submit" value="Back">
</form>
<div class="page-header">
<h1>{{post.title}}</h1>
</div>



<div class="panel panel-default">
  <div class="panel-body">
<small class="text-center"><h6>Publish time:{{ post.publishTime }}&nbsp;&nbsp; Last edited:{{ post.modifiedTime }}</h6>
<h6 class="text-center">Category:{{ post.categories.name }} &nbsp;&nbsp;Tag:
		{% for tag in post.tags%}		
			{{tag.name}}
		{% endfor %}</h6></small>
<p class="lead">&nbsp;&nbsp;&nbsp;&nbsp;{{ post.content }}</p>
  </div>
</div>

{% if post.comments %}

		{% for comment in post.comments %}
<div class="panel panel-default">
  <div class="panel-body">
	<p class="lead">{{ comment.content }}

{% if session["roleid"] == 1 or session["userid"] == comment.authorId %}
<a href="{{url_for('comment_frontend.remove',pId = post.pId , commentId = comment.id)}}" class="label label-danger">delete</a>
{% endif %}</p>
	<small >Publish time:{{ comment.publishTime }}
	
  </div>
</div>
		{% endfor %}

{% endif %}
<div class="form">
<form action="{{url_for('comment_frontend.new', id=post.pId)}}" method="post>
    {{ form.content.label }}
    {{ form.content }}
	<input class="btn btn-primary btn-block" id="submit" name="submit" type="submit" value="Comment!">
</form>
</div>

</div>
{% endblock %}