simpleblog/category/models.py
from sqlalchemy import Column,Integer,String,Text
from simpleblog.dbsettings import Base

class Category(Base):
	__tablename__ = 'Category'
	cId = Column(Integer, primary_key = True)
	name = Column(String(20), unique = True)
	description = Column(Text)

	def __repr__(self):
		return '<Category %r>' % (self.name)

	def __unicode__(self):
		return self.name

simpleblog/category/forms.py
from flask.ext.wtf import Form
from wtforms import TextField, validators, TextAreaField
from simpleblog.category.models import Category
from simpleblog.dbsettings import db_session

class CategoryCreateForm(Form):
	name = TextField('Name', [validators.required(),validators.length(min = 1, max = 20)])
	description = TextAreaField('Description')

simpleblog/category/__init__.py
from flask import Blueprint
from simpleblog.category.forms import *
from simpleblog.category.views import *
from simpleblog.category.models import *

simpleblog/category/views.py
from flask import Flask,Blueprint,render_template,redirect,url_for,request,session,flash

from simpleblog.category.models import Category
from simpleblog.account.models import User
from simpleblog.category.forms import CategoryCreateForm
from simpleblog.dbsettings import db_session

backend = Blueprint("category_backend",__name__,url_prefix="/admin",template_folder='templates')

@backend.route('/category',methods = ['GET', 'POST'])
def index():
	if "username" not in session:
		return redirect(url_for('post_frontend.index'))
	admin = User.query.filter_by(userName=session["username"]).first()
	if admin.roleId != 1:
		return redirect(url_for('post_frontend.index'))

	categories = Category.query.filter(Category.cId != 1).all()
	return render_template('category/backend/index.html', categories = categories)


@backend.route('/category/new',methods = ['GET', 'POST'])
def new():
	if 'username' not in session:
		return redirect(url_for('post_frontend.index'))
	admin = User.query.filter_by(userName=session["username"]).first()
	if admin.roleId != 1:
		return redirect(url_for('post_frontend.index'))
	form = CategoryCreateForm()

	if form.validate_on_submit():
		newcat = Category()
		form.populate_obj(newcat)
		db_session.add(newcat)
		db_session.commit()
		return redirect(url_for("category_backend.index"))
	return render_template('category/backend/new.html', form = form)

@backend.route('/category/<int:id>')
def view(id):
	if 'username' not in session:
		return redirect(url_for('post_frontend.index'))
	admin = User.query.filter_by(userName=session["username"]).first()
	if admin.roleId != 1:
		return redirect(url_for('post_frontend.index'))
	category = Category.query.filter_by(cId = id).first()
	if not category:
		return NotFound(404)
	return render_template('category/backend/view.html', category = category)

@backend.route('/category/<int:id>/edit',methods = ['GET', 'POST'])
def edit(id):
	if 'username' not in session:
		return redirect(url_for('post_frontend.index'))
	admin = User.query.filter_by(userName=session["username"]).first()
	if admin.roleId != 1:
		return redirect(url_for('category_backend.index'))

	category = Category.query.filter_by(cId = id).first()
	form = CategoryCreateForm(request.form, category)
	if form.validate_on_submit():
		form.populate_obj(category)
		db_session.commit()
		return redirect(url_for('category_backend.index'))
	return render_template('category/backend/edit.html', form=form)

@backend.route('/category/<int:id>/remove', methods=['GET','POST'])
def remove(id):
	if 'username' not in session:
		return redirect(url_for('post_frontend.index'))
	admin = User.query.filter_by(userName=session["username"]).first()
	if admin.roleId != 1:
		return redirect(url_for('post_frontend.index'))
	if id == 1:
		return redirect(url_for('category_backend.index'))
	Category.query.filter_by(cId = id).delete()
	db_session.commit()
	return redirect(url_for('category_backend.index'))

simpleblog/category/templates/category/backend/edit.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
<div class="form">
<form action="{{url_for('category_backend.index')}}" method=post>
	<input id="submit" name="submit" type="submit" value="Back">
</form>
<h2 class="form-signin-heading">Edit Category</h2>
<form action="?{{ request.query_string }}" method=post>
		{{ form.hidden_tag() }}

		{{ form.name.label }}
		{{ form.name }}

		{{ form.description.label }}
		{{ form.description }}

	<input class="btn btn-primary btn-block" id="submit" name="submit" type="submit" value="Edit">
</form>
</div>
</div>
{% endblock %}

simpleblog/category/templates/category/backend/index.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
<form action="{{url_for('category_backend.new')}}" method=post>
	<input class="btn btn-danger" id="submit" name="submit" type="submit" value="Add a new category!">
</form>
	<table class="table">
		<tr>
			<th>Category</th>
			<th>Edit</th>
			<th>Delete</th>
		</tr>
		{% for category in categories %}
		<tr>
			<td><a href="{{ url_for('category_backend.view', id=category.cId) }}">{{ category.name }}</a></td>
			<td><a href="{{ url_for('category_backend.edit', id=category.cId) }}">Edit</a></td>
			<td><a href="{{ url_for('category_backend.remove', id=category.cId) }}">Delete</a></td>
		</tr>
		{% endfor %}
	</table>
</div>
{% endblock %}

simpleblog/category/templates/category/backend/new.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
<div class="form">
<form action="{{url_for('category_backend.index')}}" method=post>
	<input id="submit" name="submit" type="submit" value="Back">
</form>
<h2 class="form-signin-heading">Create New Category</h2>
	<form action = "{{ url_for('category_backend.new') }}" method=post>
		{{ form.hidden_tag() }}

		{{ form.name.label }}
		{{ form.name }}

		{{ form.description.label }}
		{{ form.description }}

		<p><input class="btn btn-primary btn-block" id="submit" name="sumbit" type="submit" value="Create"></p>
	</form>
 </div>
</div>
{% endblock %}

simpleblog/category/templates/category/backend/view.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
<form action="{{url_for('category_backend.index')}}" method=post>
	<input id="submit" name="submit" type="submit" value="Back">
</form>
<div class="page-header">
<p>Name:{{category.name}}</p>
<p>Description:{{category.desciption}}</p>
</div>
</div>
{% endblock %}